version: "3.3"

networks:
  default:
    external:
      name: swarmstack_net

volumes:
    influxdb-data:
      driver: pxd
      driver_opts:
        repl: 2
        size: 40

services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_USER=${INFLUXDB_USER:-prometheus}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USE_PASSWORD:-prompass}
    deploy:
      mode: replicated
      replicas: 1
      labels:
        prometheus.enable: "true"
        prometheus.port: "8086"
        prometheus.path: "/metrics"
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    volumes:
      - influxdb-data:/var/lib/influxdb

